default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= MYSQL_ROOT_PASSWORD %>
  socket: <%= MYSQL_SOCKET %>

development:
  <<: *default
  database: rails-cloud-run-sample_development

test:
  <<: *default
  database: rails-cloud-run-sample_test

production:
  <<: *default
  database: sample
  username: root
  